- name: "Copy {{component}} service"
  ansible.builtin.template:
    src: "{{component}}.service.j2"
    dest: "/etc/systemd/system/{{component}}.service"

- name: deamon realod and start
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "start and enable {{component}}"
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted
    enabled: yes

# - name: "Unmask the {{component}} service"
#   ansible.builtin.systemd:
#     name: "{{component}}"
#     masked: no

# - name: "Start and enable {{component}} service"
#   ansible.builtin.systemd:
#     name: "{{component}}"
#     enabled: yes
#     state: started